#! /usr/bin/env python
# @Author : sanyapeng


str1 = "JKADFLADJFADqazwsxedcrfvtgbnhyujmkilophnfgsdfgsgsdacshsfasdgvscxgsaxbssedacghqtXDFZGCSVZOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOADOGAOFUOWTEJCXAJVOASFIOAJODFJOAHFIHAFJVADPSJVAJNOFJAOSJFA"
dict1 = {}
set1 = set(str1)
print(set1)

for i in set1:
    count = 0
    for j in str1:
        if i == j:
            count += 1
        dict1[i] = count

for k,v in dict1.items():
    print(k,v)

